"""empty message

Revision ID: 890a1e0ec216
Revises: 4b923b8ae2cd
Create Date: 2018-04-29 13:44:40.179395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '890a1e0ec216'
down_revision = '4b923b8ae2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_details', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('contact_details', 'first_name')
    op.drop_column('contact_details', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_details', sa.Column('last_name', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('contact_details', sa.Column('first_name', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('contact_details', 'name')
    # ### end Alembic commands ###
